# Generated by Django 4.0.5 on 2023-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FI', 'Fiat'), ('CHE', 'Chevrolet'), ('FO', 'Ford'), ('TO', 'Toyota')], default='FO', max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('carroceria', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('PAR', 'Particular'), ('TRAN', 'Transporte'), ('CAR', 'Carga')], default='PAR', max_length=20)),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
