# Generated by Django 4.0.5 on 2023-06-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculomodel',
            old_name='carroceria',
            new_name='serial_carroceria',
        ),
        migrations.RenameField(
            model_name='vehiculomodel',
            old_name='motor',
            new_name='serial_motor',
        ),
    ]
