# Generated by Django 4.0.5 on 2023-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculomodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
